cora:
  gamma: 1.0
  sigma: 0.01
  sample_size: 2708
  seed: 1009
  max_epoch: 300

citeseer:
  gamma: 0.1
  sigma: 0.01
  sample_size: 3327
  batch_size: 1
  seed: 1009
  max_epoch: 300
    
pubmed:
  gamma: 1.0
  sigma: 0.001
  sample_size: 8000
  seed: 1009
  max_epoch: 300
